Try fix "RuntimeError: Internal C++ object (zGeoTreeModel) already deleted."
When calling the zGeoWidget.reset_builder() function,
it sometimes show following error msg:
  RuntimeError: Internal C++ object (zGeoTreeModel) already deleted.
The zGeoTreeModel member variable seems freed by Python GC.
Don't know the root cause yet.
When play around Scene Panel 2, the component view is not reset
when create new scene.
So I make the reset component view unconditionally.
After testing, it seems this change also fix the preceding error.
So I push this change and see how it works later.